project:
  type: website
  output-dir: docs

website:
  title: "BrandonKoskie.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - dashboards.qmd
      - icon: github
        href: https://github.com/BrandonKoskie
        target: blank
      - href: https://google.com
        text: Google?

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

